Closes #4622: Add unit tests for extensions
mozilla-mobile/fenix pull request #14248
Opened 2020-08-26 21:53 UTC by NotWoods

2020-09-17 23:15 UTC, ekager requested changes
I think there are some merge conflicts in the BaseBrowserFragment :/

2020-09-17 23:15 UTC, ekager commented on app/src/test/java/org/mozilla/fenix/ext/AccessibilityManagerTest.kt
> +package org.mozilla.fenix.ext
nit - license

2020-09-29 19:04 UTC, eliserichards commented
bors try

2020-10-05 20:07 UTC, eliserichards commented
bors try

2020-10-05 20:35 UTC, eliserichards commented
bors try

2020-10-06 03:28 UTC, jonalmeida commented
It's failing at:

```
[task 2020-10-05T20:43:32.650Z] > Task :app:compileDebugUnitTestKotlin FAILED
[task 2020-10-05T20:43:32.650Z] e: /builds/worker/checkouts/src/app/src/test/java/org/mozilla/fenix/ext/LiveDataTest.kt: (22, 18): Unresolved reference: observeOnceAndRemoveObserver
[task 2020-10-05T20:43:32.749Z] 
[task 2020-10-05T20:43:32.749Z] FAILURE: Build failed with an exception.
[task 2020-10-05T20:43:32.749Z] 
[task 2020-10-05T20:43:32.749Z] * What went wrong:
[task 2020-10-05T20:43:32.749Z] Execution failed for task ':app:compileDebugUnitTestKotlin'.
[task 2020-10-05T20:43:32.749Z] > Compilation error. See log for more details
[task 2020-10-05T20:43:32.749Z] 
```

2020-10-06 19:05 UTC, eliserichards commented
The first time it was failing on the UI tests :)

2020-10-15 16:19 UTC, eliserichards commented
We're still getting a 403 from test-debug. Re-running bors

2020-10-15 16:21 UTC, eliserichards commented
bors try

2020-10-15 16:39 UTC, eliserichards commented
bors try

2020-10-15 21:32 UTC, liuche commented
@JohanLorenzo it seems like using bors to run try doesn't seem to be working here. Do you have any ideas on why this might be?

2020-10-16 21:41 UTC, liuche commented
Oh, looks like a build error?
`e: fenix/app/src/test/java/org/mozilla/fenix/ext/LiveDataTest.kt: (22, 18): Unresolved reference: observeOnceAndRemoveObserver`

2020-10-21 15:53 UTC, liuche commented
green green green green green

2020-12-14 19:18 UTC, eliserichards approved these changes
👍 yay, tests!

2021-01-25 21:44 UTC, eliserichards commented
We do not want to make changes to the BaseBrowserFragment now, so closing this.

2021-01-25 21:44 UTC, closed without merging