For #11800: Hide reveal and clear password icons if the password is empty when editing a saved login
mozilla-mobile/fenix pull request #15244
Opened 2020-09-20 20:14 UTC by joc-a

### Pull Request checklist

- 
![Before fix - Light Mode](https://user-images.githubusercontent.com/38375996/93721201-f4dcd200-fb96-11ea-9ddb-18a267fd3c5d.png)
![Before fix - Dark Mode](https://user-images.githubusercontent.com/38375996/93721203-f73f2c00-fb96-11ea-9498-aa8c5aadd958.png)
![After fix - Light Mode](https://user-images.githubusercontent.com/38375996/93721206-f8705900-fb96-11ea-9830-941f76f853cb.png)
![After fix - Dark Mode](https://user-images.githubusercontent.com/38375996/93721205-f7d7c280-fb96-11ea-8da5-7b94844711db.png)

[ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2020-09-21 16:33 UTC, ekager commented
Hi @joc-a thanks for picking this up!

So we also set errors on the username state if you have 2 logins for a site and edit one login to match the other username (ie username dupe). Let's also verify that looks correct. 

Secondly, I think we also want to get the error icon vertically aligned with the clear icon/reveal icon to match the mocks. We might be able to do this through some drawable padding (either in the layout or we can create a new layer-list drawable to pad the error icon as we need).

Let me know if this makes sense and if you have any other questions!

2020-09-21 20:53 UTC, joc-a commented
Hi @ekager !

I aligned the error icon for the password. It now looks like this:
![After fix - Light Mode](https://user-images.githubusercontent.com/38375996/93820252-8dda1e80-fc65-11ea-9adc-2d8df93a1e40.png)
![After fix - Dark Mode](https://user-images.githubusercontent.com/38375996/93820257-903c7880-fc65-11ea-9eed-5815edd4930e.png)


I will do the same thing for the username but first I'd like to know what we want it to look like when the username is a duplicate. It currently looks like this:
![Screenshot_1600721223](https://user-images.githubusercontent.com/38375996/93819982-245a1000-fc65-11ea-9e14-1bda4fda456a.png)


Also, do we want to allow saving an empty username?
![Screenshot_1600721227](https://user-images.githubusercontent.com/38375996/93820065-46539280-fc65-11ea-9626-e55e1b772d50.png)

2020-09-21 22:59 UTC, ekager commented
Thanks @joc-a this is looking great!
That's a very good question! 🤔 cc @apbitner from our UX team and @eliserichards as the eng who originally worked on this to answer these 2 questions:
1. What should the error state of the username field look like with the error icon and clear icon displayed?
2. Do we want to allow empty usernames to be saved? @eliserichards do you remember?

2020-09-22 16:16 UTC, apbitner commented
> What should the error state of the username field look like with the error icon and clear icon displayed?
It seems to me that for the password error state we are not showing the clean icon and only showing the error icon, is that correct? If so, we might as well use the same pattern for username.

2020-09-22 19:25 UTC, eliserichards commented
> Thanks @joc-a this is looking great!
> That's a very good question! 🤔 cc @apbitner from our UX team and @eliserichards as the eng who originally worked on this to answer these 2 questions:
> 
>     1. What should the error state of the username field look like with the error icon and clear icon displayed?

The only error state for username is if the username entered would make the login a duplicate of another login that the user has saved. 

>     2. Do we want to allow empty usernames to be saved? @eliserichards do you remember?

Empty usernames are valid (as an empty string, it should never be`null`)

2020-09-22 19:26 UTC, eliserichards commented
I agree with @apbitner that we shouldn't show the username `clear` icon if there's a username error 👍

2020-09-22 21:43 UTC, ekager commented on app/src/main/res/drawable/mozac_ic_warning_with_bottom_padding.xml
> +<?xml version="1.0" encoding="utf-8"?>
nit - this needs license text at the top, look at any other xml file and copy it :)

2020-09-22 21:43 UTC, ekager commented on app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt
> +            layout.setErrorIconTintList(ColorStateList.valueOf(ContextCompat.getColor(requireContext(), R.color.design_error)))
L244 and L261 are hitting the max line length error, you can autoformat with Android Studio or just manually break it into multiple lines!

2020-09-22 21:48 UTC, ekager requested changes
Looking good! Just pulled it down and left 2 comments of things we need to change.

2020-09-23 16:08 UTC, ekager approved these changes
Looks good! Thanks for the contribution!

2020-09-23 16:42 UTC, joc-a commented
This was my first time contributing to Fenix and my second time contributing on GitHub. Thanks for being friendly and making it a pleasant experience! @ekager 
I do have a question: can external contributors rebase on master when they're done, or is that something you'd rather do internally?

2020-09-23 17:25 UTC, ekager commented
I can squash and merge when the PR passes CI!

2020-09-23 19:10 UTC, merged