For #15403 - Adds a secret debug info screen in settings
mozilla-mobile/fenix pull request #15540
Opened 2020-09-29 16:04 UTC by boek

<img width="771" alt="image" src="https://user-images.githubusercontent.com/1250545/94583737-aa142780-0232-11eb-905e-1c6000979338.png">
This will show the device/user id if they exist

2020-09-29 18:39 UTC, Amejia481 approved these changes
🚢

2020-09-29 19:07 UTC, eliserichards requested changes
Just one small nit :)

2020-09-29 19:07 UTC, eliserichards commented on app/src/main/java/org/mozilla/fenix/settings/SecretDebugSettingsFragment.kt
> + * Lets the user customize Private browsing options.
Could you add a bit more here? I don't think this description matches my understanding of what this settings menu is doing

2020-10-01 19:05 UTC, boek commented
@eliserichards nits have been fixed, just need the green check :)

2020-10-12 03:46 UTC, gabrielluong approved these changes
Just wanted to bump this! I am sure @st3fan will be happy to see this land!

2020-10-12 03:46 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/settings/SecretDebugSettingsFragment.kt
> +                    "No User Id"
Should we add these strings to static_strings as well?

2020-10-12 03:46 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/settings/SecretDebugSettingsFragment.kt
> +                    "No Device Id"
Same as above.

2020-10-13 13:13 UTC, st3fan commented
Super happy :-)

2020-12-11 19:58 UTC, eliserichards approved these changes
Just fixed conflicts with the latest `master`. Once CI is green this can land and we can make @st3fan happy 😄

2020-12-11 21:13 UTC, merged