For #15508: Show error when trying to save empty or invalid bookmark URL
mozilla-mobile/fenix pull request #15674
Opened 2020-10-04 14:44 UTC by joc-a

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU  #architecture

2020-10-14 17:50 UTC, gabrielluong commented
@joc-a Thank you for the contribution! Throwing this over to get some UX feedback.

2020-10-15 14:58 UTC, apbitner commented
@gabrielluong do we have a standardized way of handling input errors like this? I think this looks fine, but ideally we should be handling all such errors the same.

For example, this is the error state for a similar situation when adding a custom search engine:
![image](https://user-images.githubusercontent.com/22176302/96147375-e1d6cc80-0ecc-11eb-888f-2a74a7119812.png)

2020-10-15 17:43 UTC, joc-a commented
> @gabrielluong do we have a standardized way of handling input errors like this? I think this looks fine, but ideally we should be handling all such errors the same.
> 
> For example, this is the error state for a similar situation when adding a custom search engine:
> ![image](https://user-images.githubusercontent.com/22176302/96147375-e1d6cc80-0ecc-11eb-888f-2a74a7119812.png)

@apbitner I followed the error state for editing Saved Logins.
![Screenshot_1602783332](https://user-images.githubusercontent.com/38375996/96166266-6ace2200-0f26-11eb-9c6d-c4fed877007a.png)

2020-10-15 18:09 UTC, apbitner approved these changes

2020-10-15 18:57 UTC, gabrielluong commented
> @gabrielluong do we have a standardized way of handling input errors like this? I think this looks fine, but ideally we should be handling all such errors the same.

I have no idea about any input error handling.

2020-10-15 19:23 UTC, apbitner commented
> > @gabrielluong do we have a standardized way of handling input errors like this? I think this looks fine, but ideally we should be handling all such errors the same.
> 
> I have no idea about any input error handling.

@joc-a used the pattern from editing logins so that's good. Just wanted to make sure we weren't starting from scratch when we have error handling elsewhere in the app.

2020-10-17 00:55 UTC, liuche commented
@joc-a when pushing PRs, can you also run the pre-push hook? it looks like this is failing our linter.
Instructions for setting it up are [here](https://github.com/mozilla-mobile/fenix/#pre-push-hooks) (or you can also look through [the file itself](https://github.com/mozilla-mobile/fenix/blob/master/config/pre-push-recommended.sh) and see what's in it!)

2020-10-18 19:21 UTC, joc-a commented
> @joc-a when pushing PRs, can you also run the pre-push hook? it looks like this is failing our linter.
> Instructions for setting it up are [here](https://github.com/mozilla-mobile/fenix/#pre-push-hooks) (or you can also look through [the file itself](https://github.com/mozilla-mobile/fenix/blob/master/config/pre-push-recommended.sh) and see what's in it!)

@liuche Done, thanks!

2020-10-21 20:26 UTC, gabrielluong requested changes

2020-10-21 20:26 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
> -        progress_bar_bookmark.visibility = View.INVISIBLE
I think we should consider keeping this here since we call it in both 270 and 279 now.

2020-10-21 20:26 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/library/bookmarks/edit/EditBookmarkFragment.kt
> +                    inputLayoutBookmarkUrl.error
nit: I think this was left here unintentionally?

2020-10-21 22:35 UTC, gabrielluong approved these changes

2020-10-22 21:22 UTC, merged