Closes #15816 - Attempt to handle 'allowInPrivate..' pref with detached context
mozilla-mobile/fenix pull request #15880
Opened 2020-10-13 21:38 UTC by grigoryk

cc @Amejia481 since you care about addons.

@ekager one more of these lifecycle gone awry things.  

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2020-10-14 23:48 UTC, Amejia481 requested changes
Thanks for the patch, left a comment :)

2020-10-14 23:48 UTC, Amejia481 commented on app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
> +                        weakApplicationContext.get()?.components?.addonManager?.setAddonAllowedInPrivateBrowsing(
I would prefer if we could use [runIfFragmentIsAttached](https://github.com/mozilla-mobile/fenix/blob/ea2bb0df75c407e98618838cf39f90ee8bc421d9/app/src/main/java/org/mozilla/fenix/addons/Extensions.kt#L32) extension function as using `requireActivity()` when the fragment is initialized could cause crashes :)

2020-10-27 20:01 UTC, csadilek approved these changes
👍

2020-10-27 20:18 UTC, Amejia481 approved these changes

2020-10-27 20:18 UTC, merged