For #13427 - Disable the "selected tab" decoration when in Multiselect
mozilla-mobile/fenix pull request #16370
Opened 2020-11-04 16:07 UTC by Mugurell

Selecting a tab while in Multiselect would add a different decoration to the one
already set for the last tab opened and this would confuse users.
Let's avoid this.

After the changes here which are based on https://github.com/mozilla-mobile/android-components/pull/8894:
![WhatTheNewTabTrayPartialBindHelpsWithOnFenix](https://user-images.githubusercontent.com/11428869/98135393-7464fd00-1ec8-11eb-9a02-b90de7668cab.gif)
[video](https://drive.google.com/file/d/1bCmA3vKj2oWuCDwLfluvf7_kcKxsBtik/view?usp=sharing)

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR does not include any a11y user facing features.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2020-11-12 12:43 UTC, codrut-topliceanu requested changes
I think we need to make the same check regarding the decoration when the view is created. At the moment if the "current-tab" is not in view when we switch to multiselect then bringing the "current-tab" into view will apply the original decoration:

![multi select](https://user-images.githubusercontent.com/60002907/98941469-55342400-24f5-11eb-8890-6ade68e2c01a.gif)

2020-12-07 12:59 UTC, codrut-topliceanu requested changes
Gridview works great. 👍 
But there is still a bit of an issue with the listview mode.

![listview_decoration](https://user-images.githubusercontent.com/60002907/101353677-a5a46480-389c-11eb-8030-83b1fa550ee6.gif)

2020-12-07 13:47 UTC, codrut-topliceanu approved these changes
Scratch that, there was an issue with AC on my end.

Work great. 👍

2020-12-08 18:27 UTC, csadilek commented
We will land as part of https://github.com/mozilla-mobile/fenix/pull/16921 as we need an A-C upgrade with multiple changes.

2020-12-08 18:27 UTC, closed without merging