Closes #16345: Standartizing share icon across all app
mozilla-mobile/fenix pull request #16536
Opened 2020-11-12 20:02 UTC by LeoMaldonado

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

This PR closes #16345. I removed share icon outlined by a filled share icon and put it in all references to share icons.

![Screenshot_20201112-165052](https://user-images.githubusercontent.com/1688902/98990102-cb8e5180-2508-11eb-9936-fc254c90b407.png)
![Screenshot_20201112-165153](https://user-images.githubusercontent.com/1688902/98990107-ccbf7e80-2508-11eb-826f-cd8451b70acc.png)
![Screenshot_20201112-165258](https://user-images.githubusercontent.com/1688902/98990109-cd581500-2508-11eb-93e9-c43e24403a5a.png)

2020-11-12 20:06 UTC, ekager requested changes
Could we just remove the `ic_hollow_share` altogether and use the AC `mozac_ic_share` when needed? The only drawback I can think of is we need to make sure it's tinted correctly where used.

2020-11-12 20:06 UTC, ekager commented on app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
> -        registerForIsBookmarkedUpdates()
Why are we removing this?

2020-11-12 20:20 UTC, LeoMaldonado commented
> Could we just remove the `ic_hollow_share` altogether and use the AC `mozac_ic_share` when needed? The only drawback I can think of is we need to make sure it's tinted correctly where used.

You're right, but `mozac_ic_share` belongs to a third party lib, and does not follow app theme. I decided this approach because I could use `primaryText` as default color, automatically following any future color changes

2020-11-12 20:21 UTC, LeoMaldonado commented on app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
> -        registerForIsBookmarkedUpdates()
Don't know, putting it back

2020-11-13 01:36 UTC, ekager commented
bors try

2020-11-13 01:49 UTC, ekager approved these changes
Okay I'm fine with changing the asset!

2020-11-13 01:49 UTC, ekager commented
bors r+

2020-11-13 03:57 UTC, merged

2020-11-13 03:57 UTC, ekager commented
Merged, thanks for the contribution!