For #16541: Download UX Updates
mozilla-mobile/fenix pull request #16816
Opened 2020-12-02 18:08 UTC by kglazko

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2020-12-02 18:23 UTC, kglazko commented
![DownloadDemoGif](https://user-images.githubusercontent.com/1676235/100914783-5c14dd80-3488-11eb-8d42-a855e1b8bc08.gif)
@apbitner Tagging you to take a look at the changes

2020-12-02 18:24 UTC, kglazko commented
![DownloadsUXChanges](https://user-images.githubusercontent.com/1676235/100914911-8a92b880-3488-11eb-9b86-9ef4869ea2b4.gif)
@apbitner Sorry for the email spam, uploaded the wrong GIF last time, tagging you to take a look at the changes!

2020-12-02 21:46 UTC, apbitner commented
@kglazko Looks great! I think the only thing missing is: Change the empty state copy to `No downloaded files`. Thank you!

2020-12-07 19:59 UTC, eliserichards requested changes

2020-12-07 19:59 UTC, eliserichards commented on app/src/main/res/values/strings.xml
> +    <string name="download_delete_multiple_items_snackbar">Downloads Removed</string>
Change the string name so that the change gets pushed upstream to translators

2020-12-07 19:59 UTC, eliserichards commented on app/src/main/res/values/strings.xml
> +    <string name="download_empty_message">No downloaded files</string>
Same as above

2020-12-07 19:59 UTC, eliserichards commented on app/src/main/res/values/strings.xml
> +    <string name="download_delete_item">Remove</string>
Same as above

2020-12-08 19:16 UTC, eliserichards approved these changes
Great! Let's get this merged! 🚀

2020-12-08 19:35 UTC, merged