For 16541: Remove All Downloads From Settings
mozilla-mobile/fenix pull request #16971
Opened 2020-12-10 19:58 UTC by kglazko

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2020-12-10 22:18 UTC, Amejia481 requested changes
It's looking good lets add some test to avoid future regressions. 👍🏽 
Just to confirm, do this functionality also have to show in the "Delete Browsing data on quit"  fragment? As I see that we are modifying the `deleteAndQuit` function but I don't it on the ui.

2020-12-10 22:18 UTC, Amejia481 commented on app/src/main/java/org/mozilla/fenix/utils/Settings.kt
> +    )
Let's add tests to `SettingsTest` to verify this new behaviour :)

2020-12-10 22:18 UTC, Amejia481 commented on app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteAndQuit.kt
> +        DeleteBrowsingDataOnQuitType.DOWNLOADS -> deleteDownloads()
Let's add test to `DeleteAndQuitTest` to verify this new behaviour :)

2020-12-10 22:28 UTC, Amejia481 commented
> It's looking good lets add some test to avoid future regressions. 👍🏽
> Just to confirm, do this functionality also have to show in the "Delete Browsing data on quit" fragment? As I see that we are modifying the `deleteAndQuit` function but I don't it on the ui.

It looks like we have the same entries: 

![screenshot-1607639238028](https://user-images.githubusercontent.com/773158/101837386-fae6ad00-3b0c-11eb-8793-e65acd80dfc4.jpg)

![screenshot-1607639292995](https://user-images.githubusercontent.com/773158/101837500-1f428980-3b0d-11eb-92b7-a21b22917b5c.jpg)

2020-12-11 16:13 UTC, eliserichards requested changes
This looks awesome! Just two small nits and the tests Arturo mentioned, and this is good to go! 🚀

2020-12-11 16:13 UTC, eliserichards commented on app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
> +            requireComponents.useCases.downloadUseCases.removeAllDownloads,
(This is such a small nit)
Could we make a val for `requireComponents.useCases` and `requireComponents.core` so we can just say `useCases.downloadUseCases.[...]` or `core.store`?

2020-12-11 16:13 UTC, eliserichards commented on app/src/main/res/values/strings.xml
> +    <!-- Title for the downloads item in Delete browsing data -->
Could we change this description a bit? Proposal: Title for the deleting downloads item in Delete browsing data 

Update: oh strings here are all following that pattern.. we should try to change those at some point to make them a bit more descriptive 😄

2020-12-18 22:03 UTC, Amejia481 approved these changes

2021-01-13 20:49 UTC, eliserichards approved these changes
This looks great! You did an awesome job 🎉 🎉 🎉

2021-01-19 22:21 UTC, merged