For #16519: Add space above Delete Downloads and Delete History buttons
mozilla-mobile/fenix pull request #17358
Opened 2021-01-07 20:10 UTC by joc-a

add space above Delete Downloads and Delete History buttons

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-01-11 13:13 UTC, Mugurell commented
Thank you for this patch @joc-a!
But I'm not sure these changes are needed anymore.
- The "Delete downloads" button is not used anymore following https://github.com/mozilla-mobile/fenix/issues/16541. I've created https://github.com/mozilla-mobile/fenix/issues/17393 to know for sure if the related code can be removed.
- And regarding "Delete history" I don't see any recent change that could regress the UI. Will ask UX in the ticket if any changes are needed but for the moment let's put this on stand-by.

2021-01-11 13:15 UTC, Mugurell requested changes
Thank you for this patch @joc-a!
But I'm not sure these changes are needed anymore.
- The "Delete downloads" button is not used anymore following #16541. I've created #17393 to know for sure if the related code can be removed.
- And regarding "Delete history" I don't see any recent change that could regress the UI. Will ask UX in the ticket if any changes are needed but for the moment let's put this on stand-by.

2021-01-15 10:49 UTC, joc-a commented
> Thank you for this patch @joc-a!
> But I'm not sure these changes are needed anymore.
> 
> * The "Delete downloads" button is not used anymore following #16541. I've created #17393 to know for sure if the related code can be removed.
> * And regarding "Delete history" I don't see any recent change that could regress the UI. Will ask UX in the ticket if any changes are needed but for the moment let's put this on stand-by.

@Mugurell I removed the change for "Delete downloads" 🙂

2021-01-15 12:12 UTC, Mugurell commented
> @Mugurell I removed the change for "Delete downloads" 🙂

Thank you for following this!

It looks good, UX approved, I'll help merge it.

2021-01-15 12:12 UTC, Mugurell approved these changes

2021-01-15 16:32 UTC, merged