For #17044: Explicitly set a new default engine when default is deleted.
mozilla-mobile/fenix pull request #17486
Opened 2021-01-15 14:14 UTC by mcarare

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-01-15 14:32 UTC, Amejia481 requested changes
Looks great ✨ , could we add some tests to verify this behavior and avoid future regressions?

2021-01-15 19:11 UTC, mcarare commented
@Amejia481 I also added some tests.

2021-01-20 14:52 UTC, Amejia481 approved these changes
Just one nit, after that is good to ship 🚢 !

2021-01-20 14:54 UTC, mcarare commented on app/src/test/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreferenceTest.kt
> +package org.mozilla.fenix.settings.search
Forgot about that. I was almost sure there was a lint for the license. 🤔

2021-01-20 15:20 UTC, Amejia481 commented on app/src/test/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreferenceTest.kt
> +package org.mozilla.fenix.settings.search
Yes, I thought we have a linter too, we could open a bug to investigate, maybe is not running for some reasons

2021-01-20 15:33 UTC, merged

2021-01-22 10:52 UTC, pocmo commented
@mcarare Can we please revert this and discuss this? The use case is for explicitly recording a user selection (and is getting persisted). In this case the user did not make this selection. We only persist user choices to have the ability to switch the default if it was *not* a user choice.