Hiding the usernameview if the data item.username is blank.
mozilla-mobile/fenix pull request #17784
Opened 2021-02-03 07:53 UTC by abhi951990

For issue #8605 

The issue is if the 'userview' TextView is empty, then the other TextView is not consistent with other areas in the app as mentioned in the issue. The 'webAddressView' stays on the Top and does not center the parent view.

Issue screenshot:
![image](https://user-images.githubusercontent.com/10706659/106714375-9f86e780-65b0-11eb-89e6-d29d4c956564.png)

After resolving the issue screenshot:
![image](https://user-images.githubusercontent.com/10706659/106714879-4a97a100-65b1-11eb-8808-c685b7201eda.png)

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-02-03 15:08 UTC, ekager requested changes
Thanks! Let's clean this up a tiny bit

2021-02-04 03:53 UTC, abhi951990 commented on app/src/main/java/org/mozilla/fenix/settings/logins/view/LoginsListViewHolder.kt
> +        if (item.username.isEmpty()) {
Done

2021-02-06 00:42 UTC, ekager commented on app/src/main/java/org/mozilla/fenix/settings/logins/view/LoginsListViewHolder.kt
> +        if (item.username.isEmpty()) {
Ah right sorry for the typo!

2021-02-06 00:42 UTC, ekager approved these changes
Looks good, let's get it merged!

2021-02-06 20:20 UTC, merged

2021-02-06 20:20 UTC, ekager commented
Congrats on your first PR!