Bug 1674442 Add a "visual-metrics" tag to the browsertime visual-metrics data
mozilla-mobile/fenix pull request #17900
Opened 2021-02-08 08:32 UTC by alexandru-io

Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1674442

2021-02-08 15:43 UTC, gmierz requested changes
We should be adding a tag, not an extra option.

2021-02-09 14:53 UTC, gmierz approved these changes

2021-02-09 14:53 UTC, gmierz commented
This is ready for landing now

2021-02-12 07:50 UTC, Mugurell commented
Seems like an unrelated `restoreTabCrashedReporterTest` ui test failing.
Restarting the CI tasks.

2021-02-12 21:52 UTC, merged