For #18102: Implement TestLifecycleApplication interface.
mozilla-mobile/fenix pull request #18124
Opened 2021-02-23 12:52 UTC by mcarare

@mcomella 

I tried running the test in isolation, a single time and then multiple times. It appears that after the first run, `application.onCreate()` was not called for the following runs. Looking in the [link](https://robolectric.blogspot.com/2013/04/the-test-lifecycle-in-20.html) you provided in the comments I see that the steps are run **if** you implement `TestLifecycleApplication `. 
Maybe the intermittence of the test is determined by the order the test runs. I suspected that another test calls `application.onCreate()` and Robolectric does not call it again for our test. 

With this change of the test, I did not get any failures with multiple runs / random groups of tests ran before. Let's see if it passes on CI too. 

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-02-23 13:29 UTC, mcarare commented
All tests passed on the first run.

2021-02-23 22:32 UTC, mcomella requested changes
It was an interesting idea but it doesn't seem to work for me. As per Sebastian's suggestion, I used AS' "run unit test until failure" functionality to reproduce the failure (see [this Matrix message in #android-tips](https://matrix.to/#/!DFCuKPUwKFvGJvTyvP:mozilla.org/$c3mISTKdMkQLPwhCB0hDelyZYvrk16DQ53SzLUQ_XkQ?via=mozilla.org&via=matrix.org) for how to do that).

@mcarare It seems you behavior changed locally though after your changes – are you able to reproduce the failure with "run until failure"?

By the way, I would think `TestLifecycleApplication` is supposed to be implemented on `FenixRobolectricTestApplication` but I tried that and that didn't solve the problem either.

2021-02-23 22:47 UTC, mcomella commented
Sebastian also mentioned they can reproduce by adding another test to this class in https://github.com/mozilla-mobile/fenix/issues/18102#issuecomment-784349105

2021-02-23 22:53 UTC, mcomella commented
@mcarare Thanks for thinking about this – I actually don't think addressing this is a priority though so don't feel like you need to spend more time on this. See my reasoning in https://github.com/mozilla-mobile/fenix/issues/18102#issuecomment-784570811 Let me know if you disagree!

2021-02-24 07:28 UTC, closed without merging

2021-02-24 07:31 UTC, mcarare commented
@mcomella Weirdly enough, for me locally it sometimes fails after the second run, and sometimes all runs pass.