For #18507 - ensure credit card screens cannot be screenshot
mozilla-mobile/fenix pull request #18890
Opened 2021-04-09 06:22 UTC by chrishernan

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-04-09 13:02 UTC, jonalmeida commented on app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
> +        requireActivity().window.setFlags(
nit: we seem to use `addFlags`/`clearFlags` in other places, might be best to follow the same pattern there too.

2021-05-04 20:20 UTC, gabrielluong commented
@Mugurell can you take a look at this? I am not too familiar with this area. Thanks!

2021-05-11 16:14 UTC, Mugurell requested changes
Thank you for helping with this.
It generally looks good but given the importance of this feature maybe the code can be a little tighter. 
Also, to prevent against future regressions a few simple unit ensuring `FLAG_SECURE` exists at the expected lifecycle callbacks tests would be nice. We can help with this if needed.

2021-05-11 16:14 UTC, Mugurell commented on app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardsSettingFragment.kt
> +        if (!isNextDestinationCreditCardEditor) {
Seeing that `CreditCardEditorFragment` sets `FLAG_SECURE` on it's own (which is probably desired) maybe we don't need this if check and have `onStop` always remove the flag?

2021-05-11 16:14 UTC, Mugurell commented on app/src/main/java/org/mozilla/fenix/settings/creditcards/CreditCardEditorFragment.kt
> +        activity?.window?.setFlags(
As on `CreditCardSettingFragment` setting `FLAG_SECURE` here might be too late.
Ideally we should set this even before of `super.onStart` and then remove that flag in `onStop`.

2021-05-18 18:26 UTC, gabrielluong commented
Gonna open this up to allow the team to address the feedback.

2021-05-19 16:06 UTC, closed without merging