For #18591 - Make the navbar sticky
mozilla-mobile/fenix pull request #19018
Opened 2021-04-14 09:55 UTC by Mugurell

Result:

https://user-images.githubusercontent.com/11428869/114691545-773e0680-9d20-11eb-9967-3829a0736c60.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-04-14 10:16 UTC, mcarare approved these changes

2021-04-14 18:32 UTC, eliserichards requested changes

2021-04-14 18:32 UTC, eliserichards commented on app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
> +            BrowserMenuItemToolbar(listOf(back, forward, bookmark, share, refresh), isSticky = true)
We don't need to define stickiness here, since this is the old

2021-04-14 18:33 UTC, eliserichards commented on app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
> +            BrowserMenuItemToolbar(listOf(back, forward, bookmark, share, refresh), isSticky = true)
Other than that change, this is good to merge once the AC change is in 😄

2021-04-15 17:37 UTC, eliserichards approved these changes
Awesome! Once CI passes this is ready to land 🙌 💯

2021-04-15 17:37 UTC, eliserichards commented
Unit test failure: 

```
e: /home/runner/work/fenix/fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt: (163, 75): Cannot find a parameter with this name: isSticky
```

2021-04-16 13:42 UTC, Mugurell commented
Having this locally while working on other things I see the app crashing somehow related to reportSiteIssuePlaceholder in the menu.
So this should not yet land, before this is fixed in AC.

2021-04-20 13:19 UTC, Mugurell commented
Rebased on the current master which should include the needed AC code.

2021-04-20 15:51 UTC, Mugurell commented
Seeing ` The test timed out. The test ran longer than its maximum allowed duration, and was stopped. `
Trying one more time.

2021-04-20 17:29 UTC, eliserichards commented
Still timing out 🤔 I reached out in the release duty channel to see if anyone knows what's up with the timeouts

2021-04-20 18:49 UTC, eliserichards commented
> If you look at [the videos](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/5684842378148438768/executions/bs.bb7b3a0f7de6d9f/videos), the test runner gets frozen when trying to open the three-dot menu. Since this PR is changes functionality in the menu itself, my guess is that the tests are failing for good reason, or need to be updated

2021-04-22 14:24 UTC, Mugurell commented
Went through all failed tests, ran them locally just fine, updated just a few which seemed to be impacted by this change.
Hopefully the above error affecting most of them will have been just a fluke.

2021-04-22 14:25 UTC, Mugurell commented
Adding @sv-ohorvath as a reviewer for the ui tests part.

2021-04-22 14:51 UTC, sv-ohorvath approved these changes
The changes to UI tests look ok to me.

2021-04-22 16:33 UTC, eliserichards commented
Looks like one last failure. 
`openMainMenuAddToCollectionTest `: "androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: (with res-name that is "name_collection_edittext")"

2021-04-22 17:46 UTC, Mugurell commented
One unit test failing now
```
TEST: onBookmarkTabs calls navigation on DefaultNavigationInteractor
TEST: test shouldDisplay
    [Robolectric] org.mozilla.fenix.components.tips.providers.MigrationTipProviderTest.test shouldDisplay: sdk=28; resources=BINARY
    I/MonitoringInstr: Instrumentation started!
FAILURE

java.lang.AssertionError: Verification failed: call 2 of 2: AddBookmarksUseCase(child of #506#510).invoke(any(), any(), any(), any())) was not called
````

Seems to be the one tracked in https://github.com/mozilla-mobile/fenix/issues/19024. Restarting CI tasks.

2021-04-22 18:09 UTC, merged