For #19820: Specify usage of labels for a11y services.
mozilla-mobile/fenix pull request #19962
Opened 2021-06-11 06:40 UTC by mcarare

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not -> No tests needed for comments
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not -> No visual changes.
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-06-11 16:22 UTC, mcarare commented
[taskcluster:error] Task timeout after 7200 seconds. Force killing container.

2021-06-11 17:17 UTC, Delphine requested changes

2021-06-11 17:17 UTC, Delphine commented on app/src/main/res/values/strings.xml
> +    <!-- The label for the expiration date month of a credit card to be used by a11 services-->
Nit: a11y

2021-06-11 17:17 UTC, Delphine commented on app/src/main/res/values/strings.xml
> +    <!-- The label for the expiration date year of a credit card to be used by a11 services-->
Same nit: a11y

2021-06-15 17:14 UTC, Delphine approved these changes
Thank you! :)

2021-06-16 05:49 UTC, merged