New text search UI smoke tests
mozilla-mobile/fenix pull request #22545
Opened 2021-11-23 12:02 UTC by AndiAJ

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-11-23 17:48 UTC, AaronMT requested changes
Rather than reduplicate code for the try catch can we apply a `maxTries` loop (maybe 3 times) (keep the refresh in the catch)
https://stackoverflow.com/questions/59651927/recursive-call-in-try-catch-block-to-retry-n-number-of-times
https://discuss.kotlinlang.org/t/make-it-easy-to-repeat-something-until-it-succeeds-but-at-most-n-times/8097
https://github.com/mozilla-mobile/fenix/blob/main/app/src/test/java/org/mozilla/fenix/helpers/MockkRetryTestRule.kt#L30

2021-11-24 09:59 UTC, AndiAJ commented
Hi @AaronMT , made the changes please re-check, thanks! ☺️ 

`selectAndSearchTextTest` ✅ Successfully passed 50x on Firebase
`privateSelectAndSearchTextTest` ✅ Successfully passed 50x on Firebase

<details>

<summary> 📈 Results (dropdown)</summary>

Results
matrix	result	logs	details
matrix-3oz7ozxvuwmb8	success	logs	2 test cases passed
matrix-14u1nonb8xmgr	success	logs	2 test cases passed
matrix-q8d8trijespra	success	logs	2 test cases passed
matrix-3hch9sul5bi5d	success	logs	2 test cases passed
matrix-3u8qcglyyubp3	success	logs	2 test cases passed
matrix-37elevc9g39ob	success	logs	2 test cases passed
matrix-1fd22s6anwk0j	success	logs	2 test cases passed
matrix-170bqq06nvtc3	success	logs	2 test cases passed
matrix-1rdqhv7cvlstn	success	logs	2 test cases passed
matrix-23rrr26jilxkh	success	logs	2 test cases passed
matrix-1hwznjgcj5ael	success	logs	2 test cases passed
matrix-vu3s3e0kvunua	success	logs	2 test cases passed
matrix-36ys6acqgluex	success	logs	2 test cases passed
matrix-3657hyi5xvcyb	success	logs	2 test cases passed
matrix-15fglezq0jjt4	success	logs	2 test cases passed
matrix-2mazouf7pb7uj	success	logs	2 test cases passed
matrix-2qw2tiprfqf76	success	logs	2 test cases passed
matrix-chyvxaz9y4fta	success	logs	2 test cases passed
matrix-2if73rls8wo5j	success	logs	2 test cases passed
matrix-1r51972zn4zc2	success	logs	2 test cases passed
matrix-3o5hec8vjbm3z	success	logs	2 test cases passed
matrix-iv1wja6fyj7aa	success	logs	2 test cases passed
matrix-h5j5yazeqtsea	success	logs	2 test cases passed
matrix-ijeol93vn38ua	success	logs	2 test cases passed
matrix-200zv07ot2pi8	success	logs	2 test cases passed
matrix-342r5k20svs18	success	logs	2 test cases passed
matrix-23t8fx8z4nip6	success	logs	2 test cases passed
matrix-re4ha29uljxwa	success	logs	2 test cases passed
matrix-1v36906ayye3x	success	logs	2 test cases passed
matrix-2e8pyiiewoyfl	success	logs	2 test cases passed
matrix-hg8j70j8620aa	success	logs	2 test cases passed
matrix-3su8aiw7g50hy	success	logs	2 test cases passed
matrix-1akew0g88m6sc	success	logs	2 test cases passed
matrix-js9zbfhdjqu0a	success	logs	2 test cases passed
matrix-3kzl21owb6o4m	success	logs	2 test cases passed
matrix-hyl9kf4uhb6za	success	logs	2 test cases passed
matrix-1wzesvq7w3y70	success	logs	2 test cases passed
matrix-sxbknjssenu5a	success	logs	2 test cases passed
matrix-o4i9fprujog6a	success	logs	2 test cases passed
matrix-3tlhfug62aahc	success	logs	2 test cases passed
matrix-1rv4iqrcaflfw	success	logs	2 test cases passed
matrix-jyiboacokuhja	success	logs	2 test cases passed
matrix-jd7hlz84mgvaa	success	logs	2 test cases passed
matrix-2nywhsjciq295	success	logs	2 test cases passed
matrix-2vqfpfsqcr0l6	success	logs	2 test cases passed
matrix-1ot45xpl9n9y5	success	logs	2 test cases passed
matrix-2byzce0vz3g47	success	logs	2 test cases passed
matrix-2zg82tbtipa6y	success	logs	2 test cases passed
matrix-1wn740ui42qss	success	logs	2 test cases passed
matrix-1kphe5anuu67u	success	logs	2 test cases passed

</details>

2021-11-24 09:59 UTC, AndiAJ commented
Unrelated unit test failure

SUITE: org.mozilla.fenix.tabstray.browser.InactiveTabsControllerTest
  TEST: WHEN expanded THEN notify filtered card
  FAILURE

java.lang.AssertionError: Verification failed: call 1 of 1: TabsTray(#729).updateTabs(slotCapture<List>(), any())) was not called

Restarting CI.

2021-11-24 16:47 UTC, AaronMT approved these changes

2021-11-25 08:38 UTC, merged