For #18175 - Add a new total protection ETP cookies policy
mozilla-mobile/fenix pull request #22766
Opened 2021-12-09 15:28 UTC by Mugurell

@topotropic Not sure about the position and text of this new option.
Used the same position as on desktop but the same text as on Focus. 
Please advise.

<img src="https://user-images.githubusercontent.com/11428869/145424903-ed01728c-70e9-40f1-8fc6-da7368f20748.png" width="50%" />

Focus options:
<img src="https://user-images.githubusercontent.com/11428869/145422156-1edc9f47-0f82-423e-a085-94e3256463a3.png" width="50%">

Desktop options:
<img src="https://user-images.githubusercontent.com/11428869/145422062-effce52e-bd12-4c75-917e-a412a1f70d25.png">

### Pull Request checklist

- [x] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2021-12-09 15:39 UTC, Amejia481 commented
Thanks for the patch 👏🏽 , there is a dependency that we need to address before landing on Fenix, as wihtout it we will introduce some breakage to Fenix see https://github.com/mozilla-mobile/focus-android/issues/6027 and  https://github.com/mozilla-mobile/android-components/issues/10739

2021-12-09 15:40 UTC, Amejia481 commented on app/src/main/res/values/arrays.xml
> +    <string name="total_protection">total-protection</string>
To follow desktop settings we should make this our default :)

2021-12-16 14:23 UTC, Mugurell commented
Waiting for https://github.com/mozilla-mobile/android-components/pull/11399 to be merged.

2021-12-20 20:08 UTC, topotropic commented
Do you still need input here? Thanks!

2021-12-21 14:33 UTC, Mugurell commented
> Do you still need input here? Thanks!

Was interested if the cookies blocking policy - "Cross-site cookies" (Firefox's Total protection) seems okay for Fenix and 
whether we should show it as the first option in the custom ETP settings. 
(Focus and desktop which already have this option are not really in sync)

2021-12-21 19:20 UTC, topotropic commented
@Mugurell yes, that looks alright, thanks!

2021-12-27 14:55 UTC, Mugurell commented
Rebased this patch to integrate the recent changes about the new storage_access permission.

2022-01-04 14:51 UTC, Amejia481 requested changes
After chatting with the privacy team, they communicate us that we only have to enable TCP on strict mode, we should keep our existing default value for standard mode. After this change I think we can land patch :)

2022-01-04 14:55 UTC, Amejia481 commented
> After chatting with the privacy team, they communicate us that we only have to enable TCP on strict mode and private mode, we should keep our existing default value for standard mode. After this change I think we can land patch :)

To keep this setting consistent across browsers, I'll put a patch on AC, then here we will only have to remove the part that changes our default value.

2022-01-04 15:48 UTC, Amejia481 commented
> > After chatting with the privacy team, they communicate us that we only have to enable TCP on strict mode and private mode, we should keep our existing default value for standard mode. After this change I think we can land patch :)
> 
> To keep this setting consistent across browsers, I'll put a patch on AC, then here we will only have to remove the part that changes our default value.

The PR  https://github.com/mozilla-mobile/android-components/pull/11481

2022-01-05 17:47 UTC, gabrielluong commented
Please review with @athomasmoz before landing.

2022-04-06 06:17 UTC, Mugurell commented
> Will this PR bring feature parity between Firefox Desktop and Fenix regarding ETP Strict?

Final specs are still in progress.

2022-06-19 21:56 UTC, opusforlife2 commented
Specs finalised, then, since you're updating the PR?

2022-08-12 10:45 UTC, Mugurell commented
Tried updating this but I couldn't.
Will open a new PR.

2022-08-12 10:45 UTC, closed without merging

2022-08-12 18:28 UTC, opusforlife2 commented
@Mugurell The event stated "This PR was closed". It seems to occur when the source repo/branch gets deleted.