Homepage headers to compose
mozilla-mobile/fenix pull request #24367
Opened 2022-03-21 19:42 UTC by sarah541

Fixes https://github.com/mozilla-mobile/fenix/issues/23970
Fixes https://github.com/mozilla-mobile/fenix/issues/23969
Fixes https://github.com/mozilla-mobile/fenix/issues/23968

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### To download an APK when reviewing a PR:
1. click on Show All Checks,
2. click Details next to "Taskcluster (pull_request)" after it appears and then finishes with a green checkmark,
3. click on the "Fenix - assemble" task, then click "Run Artifacts".
4. the APK links should be on the left side of the screen, named for each CPU architecture

2022-03-21 20:29 UTC, sarah541 commented
Disabling 2 UI tests which will be addressed in #24315

2022-03-21 20:34 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
> +    description: String,
```suggestion
    contentDescription: String,
```
Can you also add an @param

2022-03-21 20:34 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
> +    text: String,
Maybe rename this to be `headerText`

2022-03-21 20:36 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/home/recentbookmarks/view/RecentBookmarksHeaderViewHolder.kt
> +    private fun dismissSearchDialogIfDisplayedAndShowAllClicked() {
I don't think we should combine the 2. Let's just keep the call similar to before.
```
onShowAllClick = {
            dismissSearchDialogIfDisplayed()
            interactor.onShowAllBookmarksClicked()
}
```

2022-03-21 20:38 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/home/recentvisits/view/RecentVisitsHeaderViewHolder.kt
> +        )
Let's just go with a single @Preview in `HomeSectionHeader.kt`

2022-03-21 20:39 UTC, gabrielluong commented on app/src/main/res/layout/recent_visits_header.xml
> -        android:contentDescription="@string/past_explorations_show_all_content_description_2"
I think this string can also be removed?

2022-03-21 20:40 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
> +                interactor
Can you add the named parameter for these?

2022-03-21 20:41 UTC, gabrielluong requested changes
Some minor changes, but I think we are close

2022-03-22 19:36 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
> +    description: String,
Were we unable to call this `contentDescription`?

2022-03-22 19:37 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
> + * @param (optional) onShowAllClick Action to take when show all is clicked.
```suggestion
 * @param onShowAllButtonClick Invoked when "Show all" button is clicked.
```

2022-03-22 19:38 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
> +    navController: NavController?,
Don't need this

2022-03-22 19:38 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
> +                dismissSearchDialogIfDisplayed(navController)
Don't need this

2022-03-24 22:16 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabsHeaderViewHolder.kt
> +                    interactor::onRecentTabShowAllClicked
```suggestion
                    interactor.onRecentTabShowAllClicked()
```

2022-03-24 22:22 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt
> -                view,
Can you also add these in `onViewRecycled` below?

2022-03-25 16:12 UTC, gbrownmozilla approved these changes

2022-03-25 18:28 UTC, closed without merging