Closes #25177: compose history list
mozilla-mobile/fenix pull request #25178
Opened 2022-05-09 20:50 UTC by mavduevskiy

Closes #25177 

Default state
<img width="441" alt="default_state" src="https://user-images.githubusercontent.com/92760693/167494088-87e9222b-11c4-4ede-ba38-bf662b5014fe.png">

Scrolling state
<img width="441" alt="scrolling_state" src="https://user-images.githubusercontent.com/92760693/167494076-4036d8a0-2ed9-4acf-922c-03aff04718fb.png">

Collapsed state
<img width="441" alt="collapsed_state" src="https://user-images.githubusercontent.com/92760693/167494082-9b05b914-711f-4e34-83e7-02e94cfefbcb.png">

Empty state
<img width="441" alt="empty_state" src="https://user-images.githubusercontent.com/92760693/167496083-345d7607-1e15-4aa5-9b8c-25765700d5f6.png">

2022-05-09 20:57 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/library/syncedhistory/HistoryList.kt
> +fun HistoryItem(
We have a `FaviconListItem` component that can replace this.

2022-05-09 20:58 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/library/syncedhistory/HistoryList.kt
> +fun HistoryGroupItem(
This can be replaced with a `IconListItem`

2022-05-09 20:58 UTC, csadilek requested changes

2022-05-09 20:58 UTC, csadilek commented on buildSrc/src/main/java/Dependencies.kt
> +    const val androidx_compose_paging = "1.0.0-alpha14"
Drive-by to make sure we're not landing `alpha` level dependencies.

2022-05-09 20:59 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/library/syncedhistory/HistoryList.kt
> +fun HistorySectionHeader(
This can be replaced with `ExpandableListHeader` I believe

2022-05-09 21:00 UTC, gabrielluong commented on app/src/main/java/org/mozilla/fenix/library/syncedhistory/HistoryList.kt
> +        }
This can be replaced by `ExpandableListHeader`

2022-05-19 22:33 UTC, gabrielluong commented
:construction: **Pull Request Maintenance** :construction: Closing this since I am assuming we are going with a different approach. Feel free to reopen

2022-05-19 22:33 UTC, closed without merging