For #21443: Disable history delete and search with empty history
mozilla-mobile/fenix pull request #27443
Opened 2022-10-18 06:56 UTC by fice-t

This defaults `isEmpty` to true as otherwise entering the history
fragment with no history did not disable the delete button until
another action was taken.

Note that due to the way `HistoryAdapter` determines the current empty state, the icons briefly show up as disabled before being enabled when there is history available. That's just cosmetic and could be part of a separate issue (which I can create if necessary).

https://user-images.githubusercontent.com/13156601/196357315-6e33b484-3d5b-4c6f-90db-9fe4c6747f92.mp4

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [x] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [x] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2022-12-08 00:44 UTC, MatthewTighe requested changes

2022-12-08 00:44 UTC, MatthewTighe commented on app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
> +        activity?.invalidateMenu()
I think we can revert this name change in order to keep the diff minimal - `invalidateOptionsMenu` seems fine to me

2022-12-08 00:44 UTC, MatthewTighe commented on app/src/main/java/org/mozilla/fenix/library/history/HistoryController.kt
> +    private val invalidateMenu: () -> Unit,
This parameter can keep the old name as well

2022-12-08 00:44 UTC, MatthewTighe commented on app/src/main/java/org/mozilla/fenix/library/history/HistoryFragment.kt
> +        }
I was able to replicate the desired behavior here by moving this into `onCreateMenu`, and we could avoid this additional override.  This also allowed me to switch the `isEmpty` argument to `HistoryState` back to `false`. I assume that the dispatch and call to `invalidateMenu`() in `onEmptyStateChanged` is what is causing the correct behavior

2022-12-08 00:45 UTC, MatthewTighe commented
Thanks for your contribution! Had a few small suggestions for changes 🙂

2023-01-31 17:33 UTC, boek commented
Moved original issue to Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=1814192

2023-02-13 18:54 UTC, MatthewTighe commented
Hey @fice-t, thanks so much for your contribution. As I mentioned in https://github.com/mozilla-mobile/fenix/pull/27476, we will be moving this repository to [firefox-android](https://github.com/mozilla-mobile/firefox-android) in the coming days, and won't be able review or land this PR until after the migration.

Please feel free to reopen a new PR against the new repo once migration is complete. You will have to clone the new repository and reapply your changes. Thank you again, and sorry for the inconvenience.

It looks like there were some changes requested when this PR was first opened. Please feel free to address those when and if you look to open a PR in the new repo 🙂 

For more information, please see https://github.com/mozilla-mobile/fenix/issues/26855.

2023-02-13 18:54 UTC, closed without merging