Add notification config with polling interval to messaging feature
mozilla-mobile/fenix pull request #28381
Opened 2023-01-03 19:48 UTC by jhugman

Fixes [EXP-2992](https://mozilla-hub.atlassian.net/browse/EXP-2992).

Adds a polling interval to the messaging feature.

This can be accessed via 

```kotlin
val featureConfig = FxNimbus.features.messaging.value()
val notificationConfig = featureConfig.notificationConfig

val pollingInterval = notificationConfig.pollingInterval
```

### Pull Request checklist

- [ ] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [ ] **Screenshots**: This PR includes screenshots or GIFs of the changes made or an explanation of why it does not
- [ ] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/shared-docs/blob/master/android/accessibility_guide.md) or does not include any user facing features. In addition, it includes a screenshot of a successful [accessibility scan](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en_US) to ensure no new defects are added to the product.

### QA

- [x] **QA Needed**

### To download an APK when reviewing a PR (after all CI tasks finished running):
1. Click on `Checks` at the top of the PR page.
2. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
3. Click on the `build-debug` task.
4. Click on `View task in Taskcluster` in the new `DETAILS` section.
5. The APK links should be on the right side of the screen, named for each CPU architecture.

### GitHub Automation

Used by GitHub Actions.

2023-01-04 11:39 UTC, t-p-white commented on .experimenter.yaml
> +      description: "Configuration of the notification worker, for all notification messages."
does this also require a default as nimbus.fml.yaml

2023-01-04 11:41 UTC, t-p-white commented on .experimenter.yaml
> +      description: "Configuration of the notification worker, for all notification messages."
nit:
```suggestion
      description: "Configuration of the notification worker for all notification messages."
```

2023-01-04 11:56 UTC, t-p-white commented on nimbus.fml.yaml
> +          default: 600
should this also match the default 3600?

2023-01-04 12:02 UTC, t-p-white commented on nimbus.fml.yaml
> +      - channel: developer
is the new `channel: developer` notation required to add the value, or can this be included in the above `channel: developer`?

2023-01-04 12:07 UTC, t-p-white requested changes
Great description 👍  

Newbie question - other PRs I’ve seen & created for mobile use a different branching process (like this https://github.com/mozilla-mobile/shared-docs/blob/main/android/CONTRIBUTING_code.md#creating-a-pull-request) whereas this is using a branch directly in the fenix repo - just want to clarify if this is deliberate?

2023-01-04 16:12 UTC, t-p-white approved these changes
lgtm 👍 

Shall we hold off landing until we get some feedback on the branching query?

2023-01-04 18:46 UTC, MatthewTighe commented
> lgtm 👍
> 
> Shall we hold off landing until we get some feedback on the branching query?

I've seen other people that have access levels to create branches in the repo follow this branching strategy before, for [example](https://github.com/mozilla-mobile/fenix/pull/27993) so AFAIK it's okay, but do not have an good understanding of the difference so I may not be an authority.

2023-01-05 10:19 UTC, Mugurell commented
> > lgtm 👍
> > Shall we hold off landing until we get some feedback on the branching query?
> 
> I've seen other people that have access levels to create branches in the repo follow this branching strategy before, for [example](https://github.com/mozilla-mobile/fenix/pull/27993). So AFAIK it's okay, but I do not have an good understanding of the difference so I may not be an authority.

I think this branches will remain in the project even after the patch is merged, polluting the release branches list.
I remember @rvandermeulen cleaning these from time to time, maybe he can offer more context.

2023-01-05 10:26 UTC, t-p-white commented
> > > lgtm 👍
> > > Shall we hold off landing until we get some feedback on the branching query?
> > 
> > 
> > I've seen other people that have access levels to create branches in the repo follow this branching strategy before, for [example](https://github.com/mozilla-mobile/fenix/pull/27993). So AFAIK it's okay, but I do not have an good understanding of the difference so I may not be an authority.
> 
> I think this branches will remain in the project even after the patch is merged, polluting the release branches list. I remember @rvandermeulen cleaning these from time to time, maybe he can offer more context.

Thank you @MatthewTighe and @Mugurell for your thoughts on this! I'll see if @rvandermeulen can give some steer. It'd be useful to know for future reference 👍

2023-01-05 14:02 UTC, rvandermeulen commented
AFAIK, mergify should delete the branch automatically when the PR merges. Worst-case, we can always remove it manually if it doesn't, though.

2023-01-05 14:48 UTC, t-p-white commented
> AFAIK, mergify should delete the branch automatically when the PR merges. Worst-case, we can always remove it manually if it doesn't, though.

Super, thank you for the info @rvandermeulen!

2023-01-05 16:25 UTC, t-p-white commented on nimbus.fml.yaml
> +            polling-interval: 180 # 3 minutes
Can I clarify why this is required to be 3 minutes? Reason for asking is that typically Workers are restricted by the OS with regard to how often they can be performed

2023-01-05 16:57 UTC, merged